AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: aws-books-explorer - SAM template for Lambda + API Gateway

Globals:
  Function:
    Timeout: 10

Resources:
  BooksFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: books-function
      CodeUri: backend/lambda
      Handler: index.handler
      Runtime: nodejs18.x
      MemorySize: 128
      Policies:
        - AWSLambdaBasicExecutionRole
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: !Sub arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:aws-books-explorer/*
      Environment:
        Variables:
          # Recommended: move GOOGLE_BOOKS_API_KEY to Secrets Manager and set the secret name here
          GOOGLE_BOOKS_API_KEY: ""
          GOOGLE_BOOKS_SECRET_NAME: "aws-books-explorer/GoogleBooks"
      Events:
        GetBooksApi:
          Type: Api
          Properties:
            Path: /books
            Method: get

Outputs:
  ApiUrl:
    Description: "Invoke URL for API"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/books"
